name = "TimeToLive"
uuid = "b0868c6e-cc3f-11e8-088f-97c6026971d7"
authors = ["Chris de Graaf <chrisadegraaf@gmail.com>"]
version = "0.2.0"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
